### ISSUE TITLE
Add retry mechanism for OpenAI API calls

### ISSUE THREAD

**Issue by rlouf** [normal-computing/outlines#115]
API calls fail more often than they should; we should add a retry mechanism.

**Comment by harshkumarchourasia** [comment]
Should I go ahead and add a PR for this?

**Comment by rlouf** [comment]
By all means!

**Comment by harshkumarchourasia** [comment]
[PR for retrying failed openai api calls](https://github.com/normal-computing/outlines/pull/129)
