### ISSUE TITLE
Want a link from the OpenAI Cookbook?

### ISSUE THREAD

**Issue by ted-at-openai** [normal-computing/outlines#126]
Your library looks cool. Happy to link to it from the [OpenAI Cookbook repo](https://github.com/openai/openai-cookbook) if you'd like more eyeballs. But also happy to hold off if you're still in an early development stage.

**Comment by rlouf** [comment]
Thanks! That would be awesome 😊

**Comment by ted-at-openai** [comment]
Added here: https://github.com/openai/openai-cookbook/pull/470
