### ISSUE TITLE
Feature proposal: A semantic uncertainty decorator

### ISSUE THREAD

**Issue by dpsimpson** [normal-computing/outlines#147]
## The feature

As part of its text completion feature, I think outlines should have the option to compute semantic uncertainty. (See https://arxiv.org/abs/2302.09664 for details on the methods). This would further our goals of providing tools to assess the reliability of LLM generation

## Possible implementations

There are three possible ways to do this:

1. A separate `semantic_uncertainty` function 
2. A `semantic = True` option on all completion calls in the library (this would need to have `samples > 1` otherwise there would be an error. Errors would also be thrown for controlled generation.)
3. A `@semantic_uncertainty` decorator that wraps a completion function (or reaches into a `outlines.vectorize` class to wrap the internal function) and outputs the completion and semantic uncertainty.

I think option 1 is bad. Option 2 feels like a lot of boilerplate, which I don't think is ideal. So I'm going to spec out option 3.

## The decorator structure

```python
class semantic_uncertainty:
  def __init__(self, func: Callable, model_name: str, samples: int):
    pass
  
  def __call__(self, *args, **kwargs) -> Dict[str, str, List[str], float]:
    # Bounds checks
    prompt = args[1]
    # Check prompt is a string
    # Check `samples` is in `kwargs`
    # Code happens here


    return {
      'prompt': prompt,
      'completion': completion, // The first example of the largest semantic class
      'samples': samples, // A list of k samples
      'semantic_entropy': entropy // The semantic entropy
      }
```

The call is checking that `func` has the correct parts of the signature. It would actually be nice if the completion functions had a checkable type so this would be less risky.

The return is a dictionary. This means that the output of a `@vectorize` would be a List of dictionaries. rather than a List of [Type of output of func]. It would be possible to change the output of the vectorized semantic uncertainty to something like `Dict[List[str], List[str], List[List[str]], List[float]]`, but it would require changes to `vectorize`.

I went with a maximalist set of returns because I think you will usually want all of these things together. It would also be possible to return class labels as well if that makes sense.

## Does it increase the dependencies?
No.

## Does it change any other parts of outlines?
If the vectorized output can be a List of Dictionaries? No. But some small changes to the text_completion methods to associate them with a type would make it fail more gracefully.

With a different output structure? Yes, it would need to change `outlines.vectorize`

## Who would do this?
Me.

## Documentation
There would be a case study attached as well as usual doc.

**Comment by rlouf** [comment]
The completion API will change dramatically soon (see #139) and I not sure how this will affect this proposal. Also, it seems that the semantic uncertainty method requires the use of a classifier model, how would that be integrated in the library?

**Comment by dpsimpson** [comment]
That's what the`model_name` parameter is for. I'd just use a HF model as a start, but it's easy to extend. It's a straight classifier, so `transformers.pipeline` works well.
