### ISSUE TITLE
How to use gen fields in outlines? 

### ISSUE THREAD

**Issue by arunpatro** [normal-computing/outlines#176]
One aspect of guidance programs that I like are `gen` fields. Consider this:

```python
import guidance
gpt = guidance.llms.Transformers('gpt2')

program = guidance('''
Given the description of a task, generate a python program that solves it, and the completes the unit test.

Description: {{description}}
Unit Test: {{unit_test}}
Code: {{gen 'code' do_sample=True temperature=0.5 max_tokens=300 stop='Description'}}
''', llm=gpt)

out = program(description='A function to create 10 fibonacci numbers', unit_test='xxxxxx')
```

And then we can extract the output as `out['code']`. 

How can I do this intuitively in outlines? Does outlines plan to support a gen field syntax?

**Comment by rlouf** [comment]
Would something like this work?

```python
import outlines.models as models
import outlines.text as text

@text.prompt
def unit_test_prompt(description, unit_test):
    """Given the description of a task, generate a python program that solves it, and the completes the unit test.

    Description: {{description}}
    Unit Test: {{unit_test}}
    Code: {{gen 'code' do_sample=True temperature=0.5 max_tokens=300 stop='Description'}}
    """

prompt = unit_test_prompt("A function to create 10 fibonacci numbers", "xxxxxx")
complete = models.text_completion.transformers('gpt2')
out = complete(prompt)
```

**Comment by arunpatro** [comment]
Yes, this works. This is quite simple. Another requirement would be to sample multiple completions at once. I think this could be specified like: 
```python
"{{ gen 'code' samples=10 temperature=0.5}}" 
...
out = complete(...)
...
codes = out['code']
```
`codes` should be a list because of samples > 1. Currently guidance does this incorrectly because it does generations in streams and multiple streams will interleave and the final answer (a single string) will look gibberish.

**Comment by rlouf** [comment]
Should work with 

```python 
out = complete(prompt, samples=10)
```

Then you just pass `out` to the next generator without specifying `samples` and it should be fine.

**Comment by arunpatro** [comment]
> Then you just pass out to the next generator without specifying samples and it should be fine.

This could work. 

Just to clarify, this gen field construct is not yet supported right? It doesn't work rn.

**Comment by rlouf** [comment]
> Just to clarify, this gen field construct is not yet supported right? It doesn't work rn. 

If you're asking whether outlines has an infilling DSL like guidance or LMQL have, no. It would be however easy to implement. I sketched it [here](https://twitter.com/remilouf/status/1674053125773066247?s=46) and you just reminded me to open an issue to track progress on this.

**Comment by arunpatro** [comment]
I envision a prompt template to actually have fields that are user provided or generated, aka via gen fields. Running a infilling model on it to generate outputs, and then later access them via a dictionary output. 

I do not want anything more than that, I do not want if-else-then block creation inside the prompt (hence called a program in guidance) to modify the prompt at will. We should perhaps implement all the prompt modifying business using regular python functions + jinja templating. 

I did not find `@text.infilling` yet in the API, but if you are proposing an API like that, it should be good to start with.

**Comment by arunpatro** [comment]
In tree based searches, for example if we want to solve the problem and guarantee a structured evaluation process, we can use the template: 

```
Use these numbers and basic arithmetic to get 24

Input: {{input}}
Steps:
{{gen 'step1'}}
{{gen 'step2'}}
{{gen 'step3'}}
Output: {{gen 'ans'}}
```

One way to get the outputs, is to simply run a next token prediction and complete fields until `\n`. 

The only way to get multiple combinations of step1, step2, step3, ans is to sample each of the given the previous, which can take $n^4$ iterations. If there is a way to get all these n^4 solutions in a faster way by vectorizing, batching, kv-caching that would helpful in creating System 2 solutions.

**Comment by arunpatro** [comment]
Yup you did. Indeed solving (1) will take be most RoI. I think users would want an (3) infilling api, to me it seems natural for text-completion tasks, can you show how one can do it in outlines in a simple fashion? 

Same for (2) - Will successive calling of `model.complete(prompt)` take care of the unfilled fields? I assume I need to do prompt concatenations whereever required. I am trying to gauge to complexity or implementing this in outlines.

**Comment by rlouf** [comment]
Try the following. You can step through the program and look at the shape of the outputs, `(10,)`, `(10,10)`, `(10,10,10)`. If I didn't understand correctly and you just need 10 samples for the whole sequence then remove `samples=10` in the second, third and fourth call to the model.

```python
import outlines.models as models
import outlines.text as text
import numpy as np

@text.prompt
def arithmetic_prompt(input):
    """Use these numbers and basic arithmetic to get 24

     Input: {{input}}
     Steps: """

add = np.char.add
model = models.text_completion.openai("text-davinci-003")

prompt = arithmetic_prompt("input")
step_1 = model(prompt, stop_at=["\n"], samples=10)

prompt = add(add(prompt, step_1), "\nStep 2: ")
breakpoint()
step_2 = model(prompt, stop_at=["\n"], samples=10)

prompt = add(add(prompt, step_2), "\nStep 3: ")
step_3 = model(prompt, stop_at=["\n"], samples=10)

prompt = add(add(prompt, step_3), "\nOutput: ")
ans = model(prompt, samples=10)
```

**Comment by rlouf** [comment]
I opened #182 to track the infilling DSL implementation. Feel free to take a stab at it.
