### ISSUE TITLE
How to vectorize prompt creation? 

### ISSUE THREAD

**Issue by arunpatro** [normal-computing/outlines#180]
I want to generate multiple prompts and run them via GPT. 

Can we add support for vectorizing on top of `text.prompt`? 

This gives me an error:
```python
import outlines.text as text
import outlines

@outlines.vectorize
@text.prompt
def foo(input):
    '''
    Complete the line {{input}}
    '''
    
prompts = foo(["abc", "def"])
```

**Comment by arunpatro** [comment]
Maybe it's best not to support this, given the complexity of many arguments of different types.

**Comment by rlouf** [comment]
We could implement that in the future, although I'd need to see a full example where a Python loop doesn't do the job.
