### ISSUE TITLE
Match vocab to regex

### ISSUE THREAD

**Issue by phoebeklett** [normal-computing/outlines#203]
We'd like to use the following regex to generate a haiku with the zip model. 
Regex: "(\b\w+\b\s?){5}\n(\b\w+\b\s?){7}\n(\b\w+\b\s?){5}"

We get the following error when trying to do so: 
ValueError: The vocabulary does not allow us to build a sequence that matches the input regex

How should we change the vocabulary to allow for this? 

Zip model and tokenizer: https://github.com/normal-computing/ml-exp/pull/20

**Comment by brandonwillard** [comment]
Have you tried it since https://github.com/normal-computing/outlines/pull/188 was merged?  I believe that addresses the issue via https://github.com/normal-computing/outlines/issues/184.

**Comment by rlouf** [comment]
I cut a new release a earlier, it should be in it.
