### ISSUE TITLE
Confusing examples in README

### ISSUE THREAD

**Issue by simonw** [normal-computing/outlines#218]
This example here:

https://github.com/normal-computing/outlines/blob/df993c416625808f2914dab1cce49d9392b03e90/README.md#L91-L99

It's not clear what `examples` there is or where it should come from.

Also the examples that use `models.transformers("gpt2")` only work if you first run `pip install transformers`, which isn't mentioned in the document.

**Comment by rlouf** [comment]
Will work on this, thank you for taking the time to open an issue!
