### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers'

### ISSUE THREAD

**Issue by thornewolf** [normal-computing/outlines#222]
solved by pip installing transformers. But it seems to not be declared as a dependency of the project. Is this intentional?

**Comment by rlouf** [comment]
> solved by pip installing transformers. But it seems to not be declared as a dependency of the project. Is this intentional?

It is, but we should at least mention on the README that it needs to be installed separately. Sorry about that.

**Comment by rlouf** [comment]
Related to #218

**Comment by arunpatro** [comment]
@rlouf Does that mean we should not add `ctranslate2` in the dependencies as well? Re: https://github.com/normal-computing/outlines/pull/207

**Comment by rlouf** [comment]
Yes but we should 

(1) add an exception that invites the user to install the library and how to do it 
(2) mention it in the `install` section of the README
