### ISSUE TITLE
`python>3.10` is not represented in `pyproject.toml`

### ISSUE THREAD

**Issue by davidberenstein1957** [normal-computing/outlines#234]
python `match-case` statement forces package to be `python>3.10`

**Comment by davidberenstein1957** [comment]
Not sure if it is better to slightly rewrite the code and allow for `python>=3.8` or to update the `pyproject.toml`.

**Comment by rlouf** [comment]
See my reply in #219 for the Python version. But yes, `pyproject.toml` should be updated.
